### ISSUE TITLE
Typo in model_components.GatedCNN_encoder

### ISSUE THREAD

**Issue by chemgeeklian** [PraljakReps/ProtWaveVAE#1]
In https://github.com/PraljakReps/ProtWaveVAE/blob/main/SH3_design_project/source/model_components.py
Line 206-208:

         

            for ii in range(self.num_fc):
                h = self.encoder_fully_connected[ii](enc_out)
                enc_output = self.lrelu(h)

should be 

          
  
            for ii in range(self.num_fc):
                h = self.encoder_fully_connected[ii](enc_out)
                enc_out = self.lrelu(h)

**Comment by PraljakReps** [comment]
fixed here: https://github.com/PraljakReps/ProtWaveVAE/commit/602d1f468aa2eeeacd8b9fc580075250be776fba
